blank_issues_enabled: false
contact_links:
  - name: "ImageKit Documentation"
    about: "Get the help you need to start managing your digital assets using the app."
    url: "https://imagekit.io/docs/dam/app"